### ISSUE TITLE
Configurable id for OIDC auth

### ISSUE THREAD

**Issue by matthyx** [openshift/cluster-authentication-operator#364]
Hello,

After reading https://github.com/openshift/oauth-server/issues/33 and having the same problem in my organization, I came here in order to understand the reasoning behind this [comment](https://github.com/openshift/cluster-authentication-operator/blob/2b47dccf4d1fcb52ab7bcfc826cdf8d25af92f3c/pkg/controllers/configobservation/oauth/idp_conversions.go#L258):
> // There is no longer a user-facing setting for ID as it is considered unsafe

Can you somehow justify this claim?
Otherwise I am going to submit a PR to allow this overriding to adventurous users...

**Comment by matthyx** [comment]
FYI @baldator

**Comment by stlaz** [comment]
Hi, sure. The `sub` claim is the only claim having the attributes of a UUID, and that is done by design, if an IdP breaks it, it's an obvious CVE. On top of that, again, by design, the value of the `sub` claim can never be modified by the user.

Any other id may suffer from:
- an `id` of two different users may match if, for example, they appear in two separate realms
- an `id` might be modifiable
- an `id` might become modifiable in the future thus breaking the current configuration's safety

**Comment by matthyx** [comment]
Alright, then maybe we should provide a way to bypass the fact that `/`, `:`, and `%` are not supported in user names.

Do you think replacing them with other char sequences like <slash>, ... would help?
Or use a different encoding?

**Comment by stlaz** [comment]
We need to figure something out and it's on our radar.

Whatever we do, there needs to be a way for it to be backward compatible with the previous identities. That's quite a pickle because you can't just replace the sequences with other valid characters because that might suddenly clash with previously valid objects.

A possibility would be to just encode the identity names in a way so that the names no longer include these invalid sequences. That brings a new problem - the code dealing with identities needs to be aware of both the old type and the new type of identities. However, this is already something we already dealt with in 4.6 where we used this encoding trick to hide the actual oauth access tokens from their object name. Potentially, this could be a way to go, I wonder though whether there could be an easier solution I'm not seeing yet.

**Comment by matthyx** [comment]
Awesome, let me know if you need help either to implement or test your potential solutions.

**Comment by matthyx** [comment]
ping @stlaz any update on that subject? :-)

**Comment by matthyx** [comment]
> ping @stlaz any update on that subject? :-)

ping ping, if needed I can definitely help...

**Comment by stlaz** [comment]
Sorry, feature development kept me busy.

There was unfortunately other work scheduled for the upcoming OpenShift release, but I expect to look into this problem with the beginning of the new year.

**Comment by matthyx** [comment]
Alright, thanks for the update and good luck for the 4.7 👍

**Comment by stlaz** [comment]
Here's a link to the enhancement, feel free to comment: https://github.com/openshift/enhancements/pull/590 :+1:

**Comment by matthyx** [comment]
looks like I can close this one... what's the target OpenShift release for https://github.com/openshift/oauth-server/issues/33 ?
